# HTTP 连接配置
ok:
    http:
        connect-timeout: 30
        keep-alive-duration: 300
        max-idle-connections: 200
        read-timeout: 30
        write-timeout: 30
# 腾讯云账号相关的信息配置
tencent:
    sms:
        account:
            secretId:
            secretKey:
            signName:
            smsSdkAppId:
            templateId:

# 数据库相关的信息配置
spring:
    datasource:
        url:
        username:
        password:
        driver-class-name: